/**
-- DROP TYPE IF EXISTS public.account_type;
-- Type: account_type
-- DROP TYPE IF EXISTS public.account_type;
CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');

ALTER TYPE public.account_type
    OWNER TO base410pz;


-- Table: public.classification

-- DROP TABLE IF EXISTS public.classification;

CREATE TABLE public.classification(
	classification_id INT GENERATED BY DEFAULT AS IDENTITY, 
	classification_name CHARACTER VARYING NOT NULL, 
	CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- Table: public.inventory

-- DROP TABLE IF EXISTS public.inventory;


CREATE TABLE IF NOT EXISTS public.inventory(
	inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	inv_make character varying NOT NULL,
	inv_model character varying NOT NULL,
	inv_year character(4) NOT NULL,
	inv_description text NOT NULL, 
	inv_image character varying NOT NULL,
	inv_thumbnail character varying NOT NULL,
	inv_price numeric(9,0) NOT NULL,
	inv_miles integer NOT NULL,
	inv_color character varying NOT NULL,
	classification_id integer 	NOT NULL,
	CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

ALTER TABLE IF EXISTS public.inventory 
	ADD CONSTRAINT fk_classification  FOREIGN KEY (classification_id)
	REFERENCES public.classification (classification_id) MATCH SIMPLE
	ON UPDATE CASCADE
	ON DELETE NO ACTION;



-- DROP TABLE IF EXISTS public.account;

CREATE TABLE IF NOT EXISTS public.account
(
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    account_firstname character varying COLLATE pg_catalog."default" NOT NULL,
    account_lastname character varying COLLATE pg_catalog."default" NOT NULL,
    account_email character varying COLLATE pg_catalog."default" NOT NULL,
    account_password character varying COLLATE pg_catalog."default" NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.account
    OWNER to base410pz;


-- Data for table 'Classification'
INSERT INTO public.classification(classification_name)
VALUES('Custom'),
('Sport'),
('SUV'),
('Truck'),
('Sedan');



-- 1. Insert Tony Stark
INSERT INTO public.account (
    account_firstname,
    account_lastname,
    account_email,
    account_password
)
VALUES (
    'Tony',
    'Stark',
    'tony@starkent.com',
    'Iam1ronM@n'
);

-- 2. Update Tony Stark account type
UPDATE public.account
SET account_type = 'Admin'
WHERE account_id = 1;

-- 3. Delete Tony Stark
DELETE FROM public.account
WHERE account_id = 1;

-- 4. Update GM Hummer description
UPDATE public.inventory
SET inv_description = REPLACE(
    inv_description,
    'small interiors',
    'a huge interior'
)
WHERE inv_make = 'GM'
  AND inv_model = 'Hummer';

-- 5. Inner join Sport vehicles
SELECT i.inv_make,
       i.inv_model,
       c.classification_name
FROM public.inventory i
INNER JOIN public.classification c
    ON i.classification_id = c.classification_id
WHERE c.classification_name = 'Sport';

-- 6. Update image paths
UPDATE public.inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');
